# -*- mode: python ; coding: utf-8 -*-
import os

block_cipher = None

a = Analysis(
    ['desktop_entry.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('app', 'app'),
        ('static', 'static'),
        ('.env', '.'),
    ],
    hiddenimports=[
        # agents
        'app.agents.executor',
        'app.agents.base',
        'app.agents.schemas',
        # api
        'app.api.workflows',
        'app.api.tasks',
        'app.api.approvals',
        'app.api.dashboard',
        'app.api.webhooks',
        'app.api.schedules',
        'app.api.notifications',
        'app.api.plugins',
        'app.api.sandboxes',
        'app.api.audit',
        'app.api.auth',
        # auth
        'app.auth',
        # engine
        'app.engine.state_machine',
        'app.engine.yaml_parser',
        'app.engine.condition_eval',
        'app.engine.step_executor',
        'app.engine.types',
        'app.engine.plugin',
        # integrations
        'app.integrations.github',
        'app.integrations.gitlab',
        'app.integrations.bitbucket',
        # models
        'app.models.workflow',
        'app.models.task',
        'app.models.approval',
        'app.models.step_execution',
        'app.models.user',
        'app.models.webhook',
        'app.models.audit_log',
        # schemas
        'app.schemas.workflow',
        'app.schemas.task',
        'app.schemas.approval',
        'app.schemas.dashboard',
        'app.schemas.user',
        'app.schemas.webhook',
        'app.schemas.sandbox',
        'app.schemas.schedule',
        # services
        'app.services.ws_manager',
        'app.services.notifier',
        'app.services.scheduler',
        'app.services.sandbox',
        'app.services.audit',
        # templates
        'app.templates',
        # third-party
        'fastapi',
        'fastapi.middleware',
        'fastapi.middleware.cors',
        'fastapi.staticfiles',
        'fastapi.responses',
        'starlette',
        'starlette.middleware',
        'starlette.middleware.cors',
        'starlette.middleware.base',
        'starlette.staticfiles',
        'starlette.responses',
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'aiosqlite',
        'sqlalchemy',
        'sqlalchemy.dialects',
        'sqlalchemy.dialects.sqlite',
        'sqlalchemy.ext',
        'sqlalchemy.ext.asyncio',
        'sqlalchemy.orm',
        'pydantic',
        'pydantic_settings',
        'yaml',
        'httpx',
        'anthropic',
        'openai',
        'bcrypt',
        'jose',
        'jose.jwt',
        'email_validator',
        'croniter',
        'docker',
        'aiofiles',
        'typer',
        'rich',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='agent-orch-backend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='../desktop-tauri/src-tauri/icons/icon.ico',
)
