# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['cli.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('static', 'static'),
        ('app/templates', 'app/templates'),
    ],
    hiddenimports=[
        'app.api.agents',
        'app.api.integrations',
        'app.api.approvals',
        'app.api.audit',
        'app.api.dashboard',
        'app.api.auth',
        'app.api.workflows',
        'app.api.tasks',
        'app.api.notifications',
        'app.models.agent_config',
        'app.models.approval',
        'app.models.audit_log',
        'app.models.step_execution',
        'app.models.task',
        'app.models.user',
        'app.models.workflow',
        'app.engine.state_machine',
        'app.engine.step_executor',
        'app.engine.plugin',
        'app.engine.condition_eval',
        'app.engine.yaml_parser',
        'app.agents.executor',
        'app.agents.base',
        'app.agents.schemas',
        'app.services.notifier',
        'app.services.scheduler',
        'app.services.ws_manager',
        'app.services.quality_evaluator',
        'app.integrations.github',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='agent-orch-backend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
